'use strict';

module.exports = {
  rules: {
    'array-bracket-spacing': [2, 'never'],
    'block-spacing': [2, 'always'],
    'brace-style': [2, '1tbs', { allowSingleLine: true }],
    'comma-spacing': [2, { after: true, before: false }],
    'comma-style': [2, 'last', { exceptions: { NewExpression: false } }],
    'computed-property-spacing': [2, 'never'],
    'eol-last': 2,
    'func-call-spacing': 2,
    'id-blacklist': 2,
    indent: [2, 2, { SwitchCase: 1 }],
    'jsx-quotes': 2,
    'key-spacing': 2,
    'keyword-spacing': [2, { after: true, before: true }],
    'linebreak-style': [2, 'unix'],
    'new-parens': 2,
    'no-array-constructor': 2,
    'no-multiple-empty-lines': [2, { max: 2, maxBOF: 0, maxEOF: 0 }],
    'no-new-object': 2,
    'no-tabs': 2,
    'no-trailing-spaces': 2,
    'no-unneeded-ternary': 2,
    'no-whitespace-before-property': 2,
    'nonblock-statement-body-position': 0,
    'object-curly-spacing': [2, 'always'],
    'object-curly-newline': 2,
    'operator-assignment': [2, 'always'],
    'operator-linebreak': [2, 'after'],
    'padded-blocks': [2, 'never'],
    'padding-line-between-statements': [
      2,
      { blankLine: 'always', prev: 'directive', next: '*' },
      { blankLine: 'any', prev: 'directive', next: 'directive' },
    ],
    'quote-props': [2, 'as-needed', { unnecessary: false }],
    quotes: [2, 'single', { avoidEscape: true, allowTemplateLiterals: true }],
    semi: 2,
    'semi-spacing': [
      2,
      {
        after: true,
        before: false,
      },
    ],
    'semi-style': 2,
    'space-before-blocks': 2,
    'space-before-function-paren': [
      2,
      { anonymous: 'never', named: 'never', asyncArrow: 'always' },
    ],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'space-unary-ops': 2,
    'spaced-comment': [2, 'always', { block: { balanced: true } }],
    'switch-colon-spacing': 2,
    'unicode-bom': 2,
  },
};
